### ISSUE TITLE
How to run the tool

### ISSUE THREAD

**Issue by hebamuh68** [CNIC-Proteomics/pRatio#1]
Hi,
Can u add guide to how run this tool in linux ?

**Comment by mtrevix** [comment]
Hi, pRatio is entirely written in Visual C#, and therefore can only be run in Windows environments, as happens often with software in Proteomics.

There are some workarounds to run in Linux software that is originally for Windows only. For example, I personally tested Wine:

https://wiki.winehq.org/Download


I have not tested pRatio with Wine in the last years, so I cannot be sure if it will work or perform properly. However, if you want to give it try, definitely it's a possibility. Wine itself is active and being maintained (the last release is from last month).

Best wishes,
Marco


________________________________
Da: Heba Allah. Hashim ***@***.***>
Inviato: venerdì 23 dicembre 2022, 16:30
A: CNIC-Proteomics/pRatio ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [CNIC-Proteomics/pRatio] How to run the tool (Issue #1)


⚠ External sender. Take care when opening links or attachments. Do not provide your login details.

Hi,
Can u add guide to how run this tool in linux ?
